# Generated by Django 2.2 on 2019-10-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=20)),
                ('Pavatar', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Pmail', models.EmailField(max_length=254)),
                ('Page', models.IntegerField()),
                ('Pgender', models.CharField(max_length=10)),
                ('Ppass', models.CharField(max_length=20)),
            ],
        ),
    ]
