# Generated by Django 2.2 on 2019-10-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Page',
            new_name='Patient_age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Pavatar',
            new_name='Patient_avatar',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Pgender',
            new_name='Patient_gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Pmail',
            new_name='Patient_mail',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Pname',
            new_name='Patient_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Ppass',
            new_name='Patient_pass',
        ),
    ]
