# Generated by Django 2.2 on 2019-10-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191009_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Patient_pass',
            new_name='Patient_password',
        ),
    ]
