# Generated by Django 2.2 on 2019-10-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191009_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Profile',
            fields=[
                ('Patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Patient_name', models.CharField(max_length=20)),
                ('Patient_avatar', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Patient_mail', models.EmailField(max_length=254)),
                ('Patient_age', models.IntegerField()),
                ('Patient_gender', models.CharField(max_length=10)),
                ('Patient_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
