# Generated by Django 2.2 on 2019-10-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191009_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_profile',
            name='Patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
